### ISSUE TITLE
Scroll back to view the history of what was printed

### ISSUE THREAD

**Issue by davidwesst** [davidwesst/qtty#8]
Player should be able to scroll the display to show the previously printed text

# Tasks
- [x] Display vertically stacked textboxes
- [x] Scroll the vertical stack
- [x] Autoscroll to bottom of stack

**Comment by davidwesst** [comment]
Resolved with #7
